/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    TheCount: typeof import('./components/TheCount.vue')['default']
    TheCountSync: typeof import('./components/TheCountSync.vue')['default']
  }
}
